<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJhNiTuB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJhNiTuB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJhNiTuB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJhNiTuB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJhNiTuB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JhNiTuB',
    'container.build_id' => '95d9f3d2',
    'container.build_time' => 1603619698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJhNiTuB');
